name: Continuous Integration

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install dependencies
        run: make install

      - name: Setup Laravel application
        run: php artisan key:generate

      - name: Lint the files
        run: make lint

      - name: Run the tests
        run: make test
